"""add user roles for admin access

Revision ID: ceb819fa70bf
Revises: e9d7c84a1489
Create Date: 2026-08-22 14:20:26.779662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb819fa70bf'
down_revision: Union[str, Sequence[str], None] = 'e9d7c84a1489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=10), server_default='user', nullable=False))
    op.create_check_constraint('ck_user_role', 'users', "role IN ('user', 'admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_user_role', 'users', type_='check')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
