"""add trip ordering mode

Revision ID: e9d7c84a1489
Revises: 819b7a4afd72
Create Date: 2026-08-22 14:05:35.891390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d7c84a1489'
down_revision: Union[str, Sequence[str], None] = '819b7a4afd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('ordering_mode', sa.String(length=10), server_default='date', nullable=False))
    op.create_check_constraint('ck_trip_ordering_mode', 'trips', "ordering_mode IN ('date', 'manual')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_trip_ordering_mode', 'trips', type_='check')
    op.drop_column('trips', 'ordering_mode')
    # ### end Alembic commands ###
